[package]
name = "fastobo-graphs"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"
exclude = ["obographs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
lazy_static = "1.3.0"
obofoundry = "0.2.0"
serde_json = "1.0"
serde_yaml = "0.8"
ureq = "0.10.0"
