[package]
name = "fastobo-graphs"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"
exclude = ["obographs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8"
err-derive = "0.1"
serde = { version = "1.0", features = ["derive"] }
fastobo = { version = "0.6.0", optional = true }
mashup = { version = "0.1.9", optional = true }

[dev-dependencies]
lazy_static = "1.3"
obofoundry = "0.2"
serde_json = "1.0"
serde_yaml = "0.8"
ureq = "0.11"
fastobo = "0.6.0"
mashup = "0.1.9"

[features]
default = ["obo"]
obo = ["fastobo", "mashup"]
